### ISSUE TITLE
Some separators still visible in long lists on iOS 14

### ISSUE THREAD

**Issue by stefanengel** [SchmidtyApps/SwiftUIListSeparator#3]
Hi there,

I think this is a very cool idea!

It hides most of the separators of a list in iOS 14, but some of them stay visible if the list is long. I modified the example without separators from this repository to look like this:

```
struct ListWithoutSeparator: View {
    var body: some View {
        List {
            ForEach(0..<30) { index in
                VStack {
                    Text("Item \(index)")
                }
            }
        }
        .listSeparatorStyle(.none)
        .navigationBarTitle(Text("None"))
    }
}
```

and the result looks like this:
![Bildschirmfoto 2020-09-19 um 10 47 11](https://user-images.githubusercontent.com/25851870/93663104-8b10db00-fa65-11ea-972b-5a6d154e2c0e.png)

I used Xcode 12 and iOS 14 on a simulator and on a real device.
Is there a way to hide all separators?

**Comment by livesafemike** [comment]
Unfortunately Xcode12 introduced some issues like this one in iOS14 that did not occur previously with my workaround. I am working on trying to find a new fix that hides all dividers 100% of the time. I will let you know if I figure out a new workaround.

**Comment by SchmidtyApps** [comment]
Unfortunately Xcode12 introduced some issues like this one in iOS14 that did not occur previously with my workaround. I am working on trying to find a new fix that hides all dividers 100% of the time. I will let you know if I figure out a new workaround.

**Comment by SchmidtyApps** [comment]
I have an experimental branch up and running that I believe fixes this issue. The only downside is a bit of a CPU spike when scrolling because it now listens for scrollview content offset to change and anytime it does it attempts to hide dividers again. I am going to continue working on improving the performance but if you can test it out to confirm it works I think it should be good enough to merge to master and I will open a new enhancement ticket for the performance issues.

Checkout this branch:
https://github.com/SchmidtyApps/SwiftUIListSeparator/tree/xcode12-issues

**Comment by hipwelljo** [comment]
I had the same issue and this is working really well for me!

**Comment by SchmidtyApps** [comment]
@hipwelljo Awesome glad to hear! I will go ahead and merge it to master. If you run into any more issues let me know.
